GET http://localhost:8080/productos/buscar?nombre=test
Accept: application/json

###
GET http://localhost:8080/categorias/todos
Accept: application/json

###
POST http://localhost:8080/categorias/add
Content-Type: application/json

{
  "nombre": "CatePruebas"
}

###
GET http://localhost:8080/productos/todos
Accept: application/json


###
POST http://localhost:8080/productos/add
Content-Type: application/json

{
  "nombre": "Hola Jhoan3",
  "descripcion": "Hola3",
  "precio": 100.0,
  "idCategoria": 3
}

###

