GET http://localhost:8080/productos/buscarc?nompro=Ho
Accept: application/json

###
###
GET http://localhost:8080/productos/buscar?nombre=test
Accept: application/json


###
GET http://localhost:8080/categorias/todos
Accept: application/json

###
POST http://localhost:8080/categorias/add
Content-Type: application/json

{
  "nombre": "CatePruebas"
}

###
GET http://localhost:8080/productos/todos
Accept: application/json


###
POST http://localhost:8080/productos/add
Content-Type: application/json

{
  "nombre": "Ho",
  "descripcion": "Hola3",
  "precio": 100.0,
  "idCategoria": 1
}

###

GET http://localhost:8080/productos/categoria?id_categoria=1
Accept: application/json

###
PUT http://localhost:8080/productos/update/2
Content-Type: application/json

{
  "nombre": "Hola Jhoan2",
  "descripcion": "Hola2",
  "precio": 10,
  "idCategoria": 1
}
###
DELETE http://localhost:8080/productos/delete/4
###

###
GET http://localhost:8080/productos/detail/3
###


